quarkus:
  quinoa:
    package-manager-install:
      ~: true
      node-version: 22.16.0
  http:
    port: ${PORT:8080}
    cors:
      enabled: true
      origins: /.*/
  swagger-ui:
    path: /swagger-ui
  datasource:
    db-kind: postgresql
    username: u8gbcov0lg62aq
    password: pdd4b817ff0c81a9ec81677fac9aaa2e95524c66c9122edffdaaa2b93bfc161e7
    jdbc:
      url: jdbc:postgresql://c2fbt7u7f4htth.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com:5432/d2klptuimtk2sb
